#! /usr/bin/env python
# -*- coding: utf-8 -*-

from common import *

hostname = ''
if len(sys.argv) != 2:
    hostname = raw_input('Enter your unique hostname:\n')
else:
    hostname = sys.argv[1]

startVM(hostname)
