#! /usr/bin/env python
# -*- coding: utf-8 -*-

from common import *

welcome_print('Delete your KVM virtual machine, powered by blueyi')

listAllKVM()

hostname = ''
if len(sys.argv) != 2:
    hostname = raw_input('Enter your unique hostname:\n')
else:
    hostname = sys.argv[1]

isDelete = raw_input('You want delete your following host with your heart(YES or NO) \n' + hostname + '\n')

if isDelete != 'YES':
    print("You don't really want to delete <" + hostname + "> I can't delete it")
    sys.exit(1)

deleteVM(hostname)
welcome_print('Your host has been deleted: ' + hostname)

