#! /usr/bin/env python
# -*- coding: utf-8 -*-

from common import *


welcome_print('Display all KVM virtual machine, powered by blueyi')

# list all kvm exist
listAllKVM()
print('Total: ' + str(len(hostNameList())))
