#! /usr/bin/env python
# -*- coding: utf-8 -*-

import subprocess
import sys
import os

def welcome_print(msg):
    print('*' * 70)
    print('   <<< ' + msg + ' >>>')
    print('*' * 70)

welcome_print('Disable autostart your KVM virtual machine, powered by blueyi')


# command to run and get the output
def run_cmd_reout(cmd, args=' ', con = False, isprint = True, jumperr = False):
    tcall_cmd = cmd + ' ' + args
    p = subprocess.Popen(tcall_cmd, shell=True, stdout=subprocess.PIPE, executable='/bin/bash')
    toutput = p.communicate()[0]
    if p.returncode != 0 and not jumperr:
        print('<<< ' + tcall_cmd + ' >>> run failed!')
        if not con :
            sys.exit(1)
    if isprint:
        print(toutput)
    return toutput

# path
# script path
curr_path = os.path.split(os.path.realpath(__file__))[0]
# user path
user_path = os.path.expanduser('~')

# list all kvm exist

hostname = ''
if len(sys.argv) != 2:
    hostname = raw_input('Enter your unique hostname:\n')
else:
    hostname = sys.argv[1]

image_path = '/home/blueyi/vhost/'

# hostname info
print('------' + hostname + ' infomation------')
host_info_cmd = 'virsh dominfo ' + hostname
run_cmd_reout(host_info_cmd)
disautostart_cmd = 'virsh autostart --disable ' + hostname
run_cmd_reout(disautostart_cmd)

# list all kvm exist
print('Autostart virtual machine list in the following')
run_cmd_reout('virsh list --autostart --all')

