#! /usr/bin/env python
# -*- coding: utf-8 -*-


from common import *

welcome_print('Create your KVM virtual machine, powered by blueyi')

hostname = ''
if len(sys.argv) != 2:
    hostname = raw_input('Enter your unique hostname:\n')
else:
    hostname = sys.argv[1]

cloneVM(hostname, 'ubuntuServer-4g-original')
sysprepVM(hostname, hostname)
startVM(hostname)

