#! /usr/bin/env python
# -*- coding: utf-8 -*-

from common import *

welcome_print('Clone your KVM virtual machine, powered by blueyi')

hostname = ''
cloned_hostname = ''
if len(sys.argv) != 3:
    hostname = raw_input('Enter the hostname you want to clone from:\n')
    cloned_hostname = raw_input('Enter your unique cloned hostname:\n')
else:
    hostname = sys.argv[1]
    cloned_hostname = sys.argv[2]


cloneVM(cloned_hostname, hostname)
sysprepVM(cloned_hostname, cloned_hostname, miniClear=True)
startVM(cloned_hostname)
